// Generates src/environments/runtime-config.ts from environment variables.
// - Locally: reads frontend/.env if present (API_URL=...)
// - On Cloudflare Pages: set API_URL in Settings > Environment variables.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envFile = resolve(root, '.env');
const fileVars = {};
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) fileVars[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
// Blank values count as missing.
const get = (key, fallback) => process.env[key]?.trim() || fileVars[key]?.trim() || fallback;

// On Cloudflare Pages a missing API_URL would silently ship a site pointing at localhost: fail the build instead.
if (process.env.CF_PAGES && !get('API_URL')) {
  console.error('[set-env] API_URL is not set. Add it in Cloudflare Pages > Settings > Environment variables.');
  process.exit(1);
}

const config = {
  apiUrl: get('API_URL', 'http://localhost:8080').replace(/\/+$/, ''),
};

const out = resolve(root, 'src/environments/runtime-config.ts');
// The folder only holds this generated (git-ignored) file, so it does not exist in a fresh clone.
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/set-env.mjs — do not edit or commit.\nexport const runtimeConfig = ${JSON.stringify(config, null, 2)} as const;\n`,
);
console.log(`[set-env] API_URL = ${config.apiUrl}`);
